services:
    mysql:
        image: 'mysql/mysql-server:8.0'
        ports:
            - '3306:3306'
        environment:
            MYSQL_ROOT_PASSWORD: 'root'
            MYSQL_ROOT_HOST: '%'
            MYSQL_DATABASE: 'laravel_blog'
            MYSQL_USER: 'laravel'
            MYSQL_PASSWORD: 'password'
            MYSQL_ALLOW_EMPTY_PASSWORD: 1
        volumes:
            - 'mysql-data:/var/lib/mysql'
        networks:
            - laravel
        healthcheck:
            test: ['CMD', 'mysqladmin', 'ping', '-proot']
            retries: 5
            timeout: 5s

networks:
    laravel:
        driver: bridge

volumes:
    mysql-data:
        driver: local
